### ISSUE TITLE
PA Review: Photos

### ISSUE THREAD

**Issue by dahveed15** [dahveed15/Bickr#5]
Go to /albums to view the functionality

- [x] created the CRUD functionality for users to be able to add as many photos that they want for any album that they want
- [x] decent css styling (applying masonry would be ideal. Still trying to figure that out)

**Comment by niartenyaw** [comment]
Sweet!

## Functionality

- [x] The modal should automatically close once the image is uploaded
- [x] When I delete a photo, it should reroute me, probably to its album's show

## Styling

- [x] Try something like this to style the photo index:
```css
ul.photo-list {
    display: flex;
    flex-wrap: wrap;
    justify-content: center; // center things vertically
}

.photo-list a img {
    margin: 0 10px; // Separate each picture a bit to the left and right
    max-width: 300px; // don't let pictures get wider than 300px
}
```
